# Defines the workspaces for the pnpm package manager

packages:
  # Include all applications within the apps directory
  - 'apps/*'
  # Include all shared packages within the packages directory
  - 'packages/*'
overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  ajv@<6.14.0: '>=6.14.0'
  axios@>=1.0.0 <1.15.0: '>=1.15.0'
  axios@>=1.0.0 <=1.13.4: '>=1.13.5'
  brace-expansion@<1.1.13: '>=1.1.13'
  brace-expansion@>=2.0.0 <2.0.3: '>=2.0.3'
  cookie@<0.7.0: '>=0.7.0'
  fast-xml-parser@<5.7.0: '>=5.7.0'
  fast-xml-parser@>=5.0.0 <5.3.5: '>=5.3.5'
  fast-xml-parser@>=5.0.0 <5.3.6: '>=5.3.6'
  fast-xml-parser@>=5.0.0 <5.3.8: '>=5.3.8'
  fast-xml-parser@>=5.0.0 <5.5.6: '>=5.5.6'
  fast-xml-parser@>=5.0.0 <5.5.7: '>=5.5.7'
  fast-xml-parser@>=5.0.9 <=5.3.3: '>=5.3.4'
  flatted@<3.4.0: '>=3.4.0'
  flatted@<=3.4.1: '>=3.4.2'
  follow-redirects@<=1.15.11: '>=1.16.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash@<=4.17.23: '>=4.18.0'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  lodash@>=4.0.0 <=4.17.23: '>=4.18.0'
  minimatch@<3.1.3: '>=3.1.3'
  minimatch@<3.1.4: '>=3.1.4'
  minimatch@>=9.0.0 <9.0.6: '>=9.0.6'
  minimatch@>=9.0.0 <9.0.7: '>=9.0.7'
  next@>=15.6.0-canary.0 <16.1.5: '>=16.1.5'
  next@>=16.0.0-beta.0 <16.1.5: '>=16.1.5'
  next@>=16.0.0-beta.0 <16.1.7: '>=16.1.7'
  next@>=16.0.0-beta.0 <16.2.3: '>=16.2.3'
  next@>=16.0.1 <16.1.7: '>=16.1.7'
  next@>=16.1.0-canary.0 <16.1.5: '>=16.1.5'
  nodemailer@<7.0.7: '>=7.0.7'
  nodemailer@<8.0.4: '>=8.0.4'
  nodemailer@<=7.0.10: '>=7.0.11'
  nodemailer@<=8.0.4: '>=8.0.5'
  pdfjs-dist@<=4.1.392: '>=4.2.67'
  picomatch@<2.3.2: '>=2.3.2'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  postcss@<8.5.10: '>=8.5.10'
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
  tar@<7.5.7: '>=7.5.7'
  tar@<7.5.8: '>=7.5.8'
  tar@<=7.5.10: '>=7.5.11'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  tar@<=7.5.9: '>=7.5.10'
  uuid@<14.0.0: '>=14.0.0'
  yaml@>=2.0.0 <2.8.3: '>=2.8.3'
