/**
 * @file infrastructure/lib/audio-stack.ts
 * @copyright Robert E. Taylor, Extropic Systems, 2025
 * @license MIT
 * @description Teaching audio delivery: a private S3 bucket fronted by a CloudFront
 *              distribution that only serves signed URLs. The API mints those URLs after
 *              verifying identity and evaluating pool eligibility server-side, so the
 *              signature is bound to one exact event/sub-event/index/language object.
 */

import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as origins from 'aws-cdk-lib/aws-cloudfront-origins';
import * as acm from 'aws-cdk-lib/aws-certificatemanager';
import * as route53 from 'aws-cdk-lib/aws-route53';
import * as route53_targets from 'aws-cdk-lib/aws-route53-targets';

/**
 * @interface AudioStackProps
 * @description Configuration for the audio delivery stack.
 */
export interface AudioStackProps extends cdk.StackProps {
    /** Bucket holding the .m4a masters. Never public. */
    bucketName: string;
    /** Public hostname clients stream from, e.g. audio.slsupport.link */
    audioDomainName: string;
    /** Route 53 hosted zone that owns audioDomainName, e.g. slsupport.link */
    hostedZoneName: string;
    /**
     * PEM-encoded RSA public key whose private half signs playback URLs.
     * Generated by generate-audio-keypair.sh; the private half never enters this repo.
     */
    signingPublicKeyPem: string;
}

/**
 * @class AudioStack
 * @description S3 + CloudFront + ACM + Route 53 for signed-URL audio streaming.
 * @extends cdk.Stack
 */
export class AudioStack extends cdk.Stack {
    public readonly distribution: cloudfront.Distribution;
    public readonly audioBucket: s3.Bucket;

    constructor(scope: Construct, id: string, props: AudioStackProps) {
        super(scope, id, props);

        // Access logs for the distribution. CloudFront standard logging delivers via ACL,
        // so object ownership must permit ACLs; BLOCK_ALL still blocks *public* ACLs.
        const logBucket = new s3.Bucket(this, 'AudioLogBucket', {
            blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
            encryption: s3.BucketEncryption.S3_MANAGED,
            objectOwnership: s3.ObjectOwnership.BUCKET_OWNER_PREFERRED,
            enforceSSL: true,
            lifecycleRules: [{ expiration: cdk.Duration.days(365) }],
            removalPolicy: cdk.RemovalPolicy.RETAIN,
        });

        // The audio masters. Versioned so a bad re-upload is recoverable; noncurrent
        // versions age out after 90 days.
        this.audioBucket = new s3.Bucket(this, 'AudioBucket', {
            bucketName: props.bucketName,
            blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
            encryption: s3.BucketEncryption.S3_MANAGED,
            enforceSSL: true,
            versioned: true,
            lifecycleRules: [{ noncurrentVersionExpiration: cdk.Duration.days(90) }],
            removalPolicy: cdk.RemovalPolicy.RETAIN,
        });

        // Trusted key group. Only URLs signed by the matching private key are served.
        const signingPublicKey = new cloudfront.PublicKey(this, 'AudioSigningPublicKey', {
            encodedKey: props.signingPublicKeyPem,
            comment: 'Signs teaching audio playback URLs',
        });
        const keyGroup = new cloudfront.KeyGroup(this, 'AudioKeyGroup', {
            items: [signingPublicKey],
            comment: 'Teaching audio playback URL signers',
        });

        // Query strings are deliberately excluded from the cache key. The per-request
        // audit tag (?u=) and the signed-URL parameters vary per student; including them
        // would shard the cache per student and defeat edge caching entirely. The tag
        // still lands in the access logs via cs-uri-query.
        const cachePolicy = new cloudfront.CachePolicy(this, 'AudioCachePolicy', {
            comment: 'Teaching audio: immutable objects, no per-viewer cache key',
            defaultTtl: cdk.Duration.days(30),
            minTtl: cdk.Duration.days(1),
            maxTtl: cdk.Duration.days(365),
            queryStringBehavior: cloudfront.CacheQueryStringBehavior.none(),
            headerBehavior: cloudfront.CacheHeaderBehavior.none(),
            cookieBehavior: cloudfront.CacheCookieBehavior.none(),
            enableAcceptEncodingGzip: false,
            enableAcceptEncodingBrotli: false,
        });

        const hostedZone = route53.HostedZone.fromLookup(this, 'AudioHostedZone', {
            domainName: props.hostedZoneName,
        });

        // This stack is us-east-1, which is also where CloudFront requires its cert.
        const certificate = new acm.Certificate(this, 'AudioCertificate', {
            domainName: props.audioDomainName,
            validation: acm.CertificateValidation.fromDns(hostedZone),
        });

        this.distribution = new cloudfront.Distribution(this, 'AudioDistribution', {
            comment: 'Teaching audio (signed URLs only)',
            defaultBehavior: {
                // Deliberately an imported reference, not this.audioBucket: S3Origin calls
                // grantRead() on whatever it is given, which would add a live
                // s3:GetObject grant for the unused Origin Access Identity below.
                // grantRead() on an imported bucket is a no-op, leaving the OAC policy
                // further down as the only way into this bucket.
                origin: new origins.S3Origin(
                    s3.Bucket.fromBucketName(this, 'AudioBucketOriginRef', props.bucketName)
                ),
                viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
                allowedMethods: cloudfront.AllowedMethods.ALLOW_GET_HEAD,
                cachedMethods: cloudfront.CachedMethods.CACHE_GET_HEAD,
                cachePolicy,
                // AAC is already compressed; re-compressing wastes CPU and breaks nothing useful.
                compress: false,
                trustedKeyGroups: [keyGroup],
            },
            domainNames: [props.audioDomainName],
            certificate,
            // The audience is genuinely worldwide (Americas + Europe today).
            priceClass: cloudfront.PriceClass.PRICE_CLASS_ALL,
            httpVersion: cloudfront.HttpVersion.HTTP2_AND_3,
            minimumProtocolVersion: cloudfront.SecurityPolicyProtocol.TLS_V1_2_2021,
            enableLogging: true,
            logBucket,
            logFilePrefix: 'cf/',
        });

        // --- Origin Access Control -------------------------------------------------
        // aws-cdk-lib is pinned at 2.135.0 here (the @aws-cdk/aws-apigatewayv2-alpha
        // packages used by DharmaConnectStack block an upgrade), which predates
        // S3BucketOrigin.withOriginAccessControl. Wire OAC at the L1 level instead.
        // S3Origin above still emits an unused Origin Access Identity resource. It is
        // granted nothing (see the imported-bucket note on the origin), and the bucket
        // policy below admits only the CloudFront service principal for this exact
        // distribution.
        const oac = new cloudfront.CfnOriginAccessControl(this, 'AudioOriginAccessControl', {
            originAccessControlConfig: {
                name: `${props.bucketName}-oac`,
                description: 'Teaching audio bucket access',
                originAccessControlOriginType: 's3',
                signingBehavior: 'always',
                signingProtocol: 'sigv4',
            },
        });

        const cfnDistribution = this.distribution.node.defaultChild as cloudfront.CfnDistribution;
        cfnDistribution.addPropertyOverride('DistributionConfig.Origins.0.OriginAccessControlId', oac.attrId);
        cfnDistribution.addPropertyOverride('DistributionConfig.Origins.0.S3OriginConfig.OriginAccessIdentity', '');

        this.audioBucket.addToResourcePolicy(new iam.PolicyStatement({
            sid: 'AllowCloudFrontOriginAccessControlRead',
            effect: iam.Effect.ALLOW,
            principals: [new iam.ServicePrincipal('cloudfront.amazonaws.com')],
            actions: ['s3:GetObject'],
            resources: [this.audioBucket.arnForObjects('*')],
            conditions: {
                StringEquals: {
                    'AWS:SourceArn': `arn:aws:cloudfront::${this.account}:distribution/${this.distribution.distributionId}`,
                },
            },
        }));

        new route53.ARecord(this, 'AudioAliasRecord', {
            zone: hostedZone,
            recordName: props.audioDomainName,
            target: route53.RecordTarget.fromAlias(new route53_targets.CloudFrontTarget(this.distribution)),
        });
        new route53.AaaaRecord(this, 'AudioAliasRecordV6', {
            zone: hostedZone,
            recordName: props.audioDomainName,
            target: route53.RecordTarget.fromAlias(new route53_targets.CloudFrontTarget(this.distribution)),
        });

        new cdk.CfnOutput(this, 'AudioBucketName', { value: this.audioBucket.bucketName });
        new cdk.CfnOutput(this, 'AudioDomainName', { value: props.audioDomainName });
        new cdk.CfnOutput(this, 'AudioDistributionId', { value: this.distribution.distributionId });
        new cdk.CfnOutput(this, 'AudioDistributionDomainName', { value: this.distribution.distributionDomainName });
        // Goes into the API's CLOUDFRONT_AUDIO_KEY_PAIR_ID env var.
        new cdk.CfnOutput(this, 'AudioSigningKeyPairId', { value: signingPublicKey.publicKeyId });
    }
}
